
--id / password ====== admin으로 생성해주세요 
CREATE TABLE "ADMINUSER"(
   ADMINUSERNUM NUMBER(10),
   ADMINUSERID VARCHAR2(20),
   ADMINUSERPW VARCHAR2(20),
   ADMINUSEREMAIL VARCHAR2(30),
   ADMINUSERNAME VARCHAR2(30),
   CONSTRAINTS ADMINUSER_PK PRIMARY KEY(ADMINUSERNUM)
);

CREATE SEQUENCE ADMINUSER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

INSERT INTO ADMINUSER VALUES(ADMINUSER_SEQ.NEXTVAL,'admin','admin','ddddd','어드1');
