CREATE TABLE BEAUTYSAVE(
	BTTIPSAVENUM NUMBER,
	USERID VARCHAR2(20),
	BTTIPGENDER VARCHAR2(10),
	BTTIPAGE NUMBER(3),
	BTTIPEYE VARCHAR2(20),
	BTTIPNOSE VARCHAR2(20),
	BTTIPFACESHAPE VARCHAR2(20),
	BTTIPLIP VARCHAR2(20),
	BTTIPFACETYPE VARCHAR2(20),
	BTTIPFACETONE VARCHAR2(20),
	BTTIPSEASON VARCHAR2(20), 
	BTTIPTHEME VARCHAR2(30),
	CONSTRAINTS BEAUTYSAVE_PK PRIMARY KEY(BTTIPSAVENUM),
	CONSTRAINTS BEAUTYSAVE_FK FOREIGN KEY(USERID) REFERENCES "USER"(USERID)
);

CREATE SEQUENCE BTTIPSAVE_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 1000000
  MINVALUE 1;
  
DROP TABLE BEAUTYSAVE;

SELECT * FROM BEAUTYSAVE;
  
TRUNCATE TABLE BEAUTYSAVE;