CREATE TABLE BEAUTYTIP(
	BTTIPNUM NUMBER,
	USERID VARCHAR2(20),
	BTTIPTITLE VARCHAR2(100),
	BTTIPDATE DATE,
	BTTIPCONTENT VARCHAR2(1000),
	BTTIPGENDER VARCHAR2(10),
	BTTIPAGE NUMBER(3),
	BTTIPEYE VARCHAR2(20),
	BTTIPNOSE VARCHAR2(20),
	BTTIPLIP VARCHAR2(20),
	BTTIPFACE VARCHAR2(20),
	BTTIPTYPE VARCHAR2(30),
	BTTIPTONE VARCHAR2(20),
	BTTIPSEASON VARCHAR2(20), 
	BTTIPTHEME VARCHAR2(30),
	BTTIPLIKE NUMBER(6),
	CONSTRAINTS BTTIP_PK PRIMARY KEY(BTTIPNUM),
	CONSTRAINTS BTTIP_FK FOREIGN KEY(USERID) REFERENCES "USER"(USERID)
);
INSERT INTO HR.BEAUTYTIP
(BTTIPNUM, USERID, BTTIPTITLE, BTTIPDATE, BTTIPCONTENT, BTTIPGENDER, BTTIPAGE, BTTIPEYE, BTTIPNOSE, BTTIPLIP, BTTIPFACE, BTTIPTYPE, BTTIPTONE, BTTIPSEASON, BTTIPTHEME, BTTIPLIKE)
VALUES(78, 'abcd1234', '좋아요', '', '아주좋아요', '남', 20, '', '메부리코', '', '', '', '', '', '', 0);
INSERT INTO HR.BEAUTYTIP
(BTTIPNUM, USERID, BTTIPTITLE, BTTIPDATE, BTTIPCONTENT, BTTIPGENDER, BTTIPAGE, BTTIPEYE, BTTIPNOSE, BTTIPLIP, BTTIPFACE, BTTIPTYPE, BTTIPTONE, BTTIPSEASON, BTTIPTHEME, BTTIPLIKE)
VALUES(44, 'abcd1234', '안좋아요', '', '아주 안좋아요', '여', 30, '', '복코', '', '', '', '', '', '', 0);
INSERT INTO HR.BEAUTYTIP
(BTTIPNUM, USERID, BTTIPTITLE, BTTIPDATE, BTTIPCONTENT, BTTIPGENDER, BTTIPAGE, BTTIPEYE, BTTIPNOSE, BTTIPLIP, BTTIPFACE, BTTIPTYPE, BTTIPTONE, BTTIPSEASON, BTTIPTHEME, BTTIPLIKE)
VALUES(26, 'abcd1234', '평범해요', '', '아주 평범해요', '여', 10, '', '낮은코', '', '', '', '', '', '', 0);


DROP TABLE BEAUTYTIP;

select * from beautytip;

CREATE SEQUENCE BEAUTYTIP_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

CREATE TABLE BEAUTYTIPFILES(
   FILENAME VARCHAR2(100),
   BTTIPNUM NUMBER,
   CONSTRAINTS BEAUTYTIPFILES_FK FOREIGN KEY(BTTIPNUM) REFERENCES "BEAUTYTIP"(BTTIPNUM)
);

CREATE TABLE BTMULTIFILES(
   FILENAME VARCHAR2(100),
   BTTIPNUM NUMBER,
   CONSTRAINTS BTMULTIFILES_FK FOREIGN KEY(BTTIPNUM) REFERENCES "BEAUTYTIP"(BTTIPNUM)
);

CREATE TABLE BTMULTICONTENTS(
   CONTENTS VARCHAR2(500),
   BTTIPNUM NUMBER,
   CONSTRAINTS BTMULTICONTENTS_FK FOREIGN KEY(BTTIPNUM) REFERENCES "BEAUTYTIP"(BTTIPNUM)
);

