DROP TABLE FOLLOW;
DROP SEQUENCE FOLLOW_SEQ;

CREATE SEQUENCE FOLLOW_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;

CREATE TABLE FOLLOW (
	FOLLOW_NUM NUMBER(10),
	USERNUM NUMBER(10),
	TARGET_USERNUM NUMBER(10),
	CONSTRAINTS USER_FK FOREIGN KEY(USERNUM) REFERENCES "USER"(USERNUM),
	CONSTRAINTS TARGET_FK FOREIGN KEY(USERNUM) REFERENCES "USER"(USERNUM)
);

SELECT * FROM FOLLOW;