
DESC "USER";

DROP TABLE "USER";

DROP TABLE USER_FILES;

CREATE TABLE "USER"(
	USERNUM NUMBER(10),
	USERID VARCHAR2(20) UNIQUE,
	USERPW VARCHAR2(20),
	USEREMAIL VARCHAR2(30),
	USERNAME VARCHAR2(30),
	FOLLOWERNUM NUMBER(10),
	FOLLOWINGNUM NUMBER(10),
	CONSTRAINTS USER_PK PRIMARY KEY(USERNUM)
);
INSERT INTO "USER" VALUES(USER_SEQ.NEXTVAL,'abcd1234','1234','abcd@abcd.abc','뮻ㅇ',0,0,01064722130,1);
CREATE TABLE USER_FILES(
	PROVILEIMG VARCHAR2(100),
	USERNUM,
	CONSTRAINTS USER_FILES_PK PRIMARY KEY(PROVILEIMG),
	CONSTRAINTS USER_FILES_FK FOREIGN KEY(USERNUM) REFERENCES "USER"(USERNUM)
);

SELECT * FROM "USER";	

SELECT * FROM USER_FILES;

drop sequence USER_SEQ;

CREATE SEQUENCE USER_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000;


ALTER TABLE "USER" ADD FOLLOWERNUM NUMBER(10) DEFAULT 0;
ALTER TABLE "USER" ADD FOLLOWINGNUM NUMBER(10) DEFAULT 0;

ALTER TABLE "USER" DROP COLUMN USERNICKNAME;

/* 문자 추가 */
ALTER TABLE "USER" ADD USERPHONE VARCHAR2(20);
ALTER TABLE "USER" ADD USERCK VARCHAR2(20) DEFAULT 0;


