

CREATE SEQUENCE NOTICE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 100000000;


DROP SEQUENCE NOTICE_SEQ;
DROP TABLE NOTICE;
DROP TABLE NOTICE_FILES;



1. 테이블명 변경

--ALTER TABLE NOTICE RENAME TO NOTICE_1;


-- @ 공지사항테이블
-- 넘버 
-- 공지 제목
-- 공지 내용
-- 회원아이디
-- 날짜
-- 조회수
CREATE TABLE NOTICE(
	NOTICE_NUM NUMBER(10) PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(50) NOT NULL,
	NOTICE_CONTENTS VARCHAR2(3000) NOT NULL,
	USERID VARCHAR2(20) NOT NULL,
	NOTICE_DATE DATE,
	NOTICE_READCOUNT NUMBER(10)
);





INSERT INTO NOTICE
VALUES(NOTICE_SEQ.NEXTVAL, '테스트', '테스트내용', '123', SYSDATE, 0);

INSERT INTO BOARD
VALUES(BOARD_SEQ.NEXTVAL, '테스트', '테스트내용', 'hds9638', SYSDATE, 0);

SELECT * FROM NOTICE_FILES;
SELECT * FROM NOTICE;

CREATE TABLE NOTICE_FILES(
	NOTICE_FILE_NAME VARCHAR2(100),
	NOTICE_NUM,
	CONSTRAINTS NOTICE_FILES_PK PRIMARY KEY(NOTICE_FILE_NAME),
	CONSTRAINTS NOTICE_FILES_FK FOREIGN KEY(NOTICE_NUM) REFERENCES NOTICE(NOTICE_NUM)
);

SELECT * FROM NOTICE_FILES;

/*INSERT 로 NEXTVAL 한번 사용한 후 CURRVAL 사용하기*/
SELECT BOARD_SEQ.CURRVAL FROM DUAL;




		SELECT (report_num, report_type, report_board, report_member_id, report_title, report_date)
		FROM REPORT ORDER BY REPORT_NUM DESC;






