

      
    
       
       
       
       
-- 좋아요  테이블
CREATE TABLE COMMENT_LIKE (
   commentNum NUMBER(10),
   userid VARCHAR2(50),
   PRODUCT_NUM NUMBER
);


-- 상품 리뷰 테이블
--VERSION 0.8------------------------------------------------------------------------
  CREATE TABLE "HR"."PRODUCT_COMMENT" 
   (	"COMMENT_NUM" NUMBER, 
	"PRODUCT_NUM" NUMBER, 
	"USERID" VARCHAR2(200), 
	"COMMENT_WRITE" VARCHAR2(500 BYTE), 
	"COMMENT_BLAME" NUMBER, 
	"COMMENT_POINT" NUMBER, 
	"COMMENT_DATE" DATE, 
	 PRIMARY KEY ("COMMENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PRODUCT_NUM_FK" FOREIGN KEY ("PRODUCT_NUM")
	  REFERENCES "HR"."PRODUCT" ("PRODUCT_NUM") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
 -- 추가
CREATE SEQUENCE  "HR"."PRODUCT_COMMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  

-- 시퀀스
CREATE SEQUENCE  "HR"."PRODUCT_COMMENT_SEQ"
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999;


